apiVersion: v1
kind: Pod
metadata:
  name: setup-ssh-fs
  labels:
    app: setup-ssh-fs
spec:
  containers:
  - name: triton
    image: "nvcr.io/nvidia/tritonserver:24.10-trtllm-python-py3"
    command: ["sleep", "infinity"]
    # resources:
    #   limits:
    #     nvidia.com/gpu: 1
    #   requests:
    #     nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /var/run/models
        name: model-repository
      - mountPath: /dev/shm
        name: dshm
  volumes:
    - name: model-repository
      persistentVolumeClaim:
        claimName: fileserver
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 4Ti